apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: recipe-app
  labels:
    cloud.googleapis.com/location: europe-west1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbe: "true"
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - name: recipe-app-1
        image: gcr.io/386608517597/recipe-app:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: "386608517597"
        - name: ELASTICSEARCH_URL
          value: "https://my-elasticsearch-project-ed84a6.es.europe-west1.gcp.elastic.cloud:443"
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
      serviceAccountName: serviceacount